---
services:
  ckan-worker-default:
    image: ghcr.io/keitaroinc/ckan:${CKAN_VERSION}
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
      solr:
        condition: service_healthy
        restart: true
    user: root
    env_file:
      - ${PWD}/config/db/.env
      - ${PWD}/config/ckan/.env
    volumes:
      - ckan_data:/app/data
      -  /root/baru/docker-ckan/extensions:/app/extensions
    entrypoint:
      - /bin/bash
      - -lc
      - uv pip install --system -e /app/extensions/ckanext-restrict_visibility -e /app/extensions/ckanext-statsworkflow && ckan config-tool /app/production.ini 'ckanext.xloader.site_url = http://ckan:5000' && ckan config-tool /app/production.ini 'ckanext.xloader.formats = csv application/csv xls xlsx tsv application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet ods application/vnd.oasis.opendocument.spreadsheet json application/json xml application/xml text/xml' && exec ckan -c /app/production.ini jobs worker default
    healthcheck:
      disable: true

volumes:
  ckan_data:
